import {
  CURRENT_SCHEMA_VERSION,
  MAZE_GRAPH_VERSION,
  type MazeMetrics,
  type MazeProject,
} from '../core/maze/types'

const metrics: MazeMetrics = {
  difficultyScore: 24,
  difficultyLevel: 'easy',
  estimatedSeconds: 8,
  activeCells: 4,
  reachableCells: 4,
  componentCount: 1,
  disconnectedRegions: 0,
  pathLength: 4,
  solutionRatio: 1,
  graphDistance: 3,
  deadEnds: 2,
  deadEndRatio: 0.5,
  branches: 0,
  intersections: 0,
  turns: 2,
  consecutiveTurns: 1,
  exitDecoys: 0,
  edgeCount: 3,
  loopCount: 0,
  hasLoops: false,
  solutionCount: 1,
  shapeRecognition: 1,
  minimumPassageWidth: 24,
  solvable: true,
}

export function createTestProject(
  overrides: Partial<MazeProject> = {},
): MazeProject {
  const project: MazeProject = {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    appVersion: '1.0.0',
    id: 'test-maze',
    title: '작은 미로',
    description: '테스트 미로',
    creatorDisplayName: '제작자',
    createdAt: '2026-07-30T00:00:00.000Z',
    updatedAt: '2026-07-30T00:00:00.000Z',
    seed: 'fixture-seed',
    canvas: { width: 400, height: 400, aspectRatio: '1:1' },
    grid: { rows: 2, cols: 2, minimumCellPixels: 24 },
    shape: { kind: 'basic', name: 'rectangle', inset: 0 },
    mask: { rows: 2, cols: 2, cells: [true, true, true, true] },
    mazeGraph: {
      version: MAZE_GRAPH_VERSION,
      rows: 2,
      cols: 2,
      algorithm: 'dfs',
      seed: 'fixture-seed',
      cells: [
        {
          index: 0,
          row: 0,
          col: 0,
          active: true,
          walls: { top: true, right: false, bottom: true, left: true },
        },
        {
          index: 1,
          row: 0,
          col: 1,
          active: true,
          walls: { top: true, right: true, bottom: false, left: false },
        },
        {
          index: 2,
          row: 1,
          col: 0,
          active: true,
          walls: { top: true, right: false, bottom: true, left: true },
        },
        {
          index: 3,
          row: 1,
          col: 1,
          active: true,
          walls: { top: false, right: true, bottom: true, left: false },
        },
      ],
    },
    startCell: { row: 0, col: 0 },
    endCell: { row: 1, col: 0 },
    difficulty: 'easy',
    mazeMetrics: metrics,
    visualTheme: {
      wallColor: '#172033',
      pathColor: '#ffffff',
      startColor: '#16855b',
      endColor: '#d24b4b',
      accentColor: '#3458eb',
      wallWidth: 4,
      cornerRadius: 2,
    },
    background: { kind: 'solid', color: '#ffffff' },
    gameRules: {
      mode: 'classic',
      timeLimitSeconds: null,
      allowedHints: 2,
      showDpad: true,
      soundEnabled: false,
      ghostAllowed: true,
    },
    collectibles: [],
    checkpoints: [],
    secretReveal: {
      content: { kind: 'message', message: '잘했어요!' },
      mode: 'on-complete',
      animation: 'fade',
    },
    creatorReplay: {
      durationMs: 2_000,
      completed: true,
      frames: [
        { row: 0, col: 0, atMs: 0 },
        { row: 0, col: 1, atMs: 600, direction: 'right' },
        { row: 1, col: 1, atMs: 1_200, direction: 'down' },
        { row: 1, col: 0, atMs: 2_000, direction: 'left' },
      ],
    },
    exportSettings: {
      scale: 2,
      transparentBackground: false,
      includeEndpoints: true,
      includeSolution: false,
      printOrientation: 'portrait',
      printTitle: true,
      printNameField: true,
      printAnswerSheet: true,
    },
    attribution: null,
    remixAllowed: true,
  }
  return { ...project, ...overrides }
}
