import { expect, test } from '@playwright/test'

test('deep porcelain basin renders conserved water, pauses and drains without losing its maze', async ({ page }, testInfo) => {
  test.setTimeout(180_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => {
    if (message.type() === 'error') errors.push(message.text())
  })
  await page.goto('/')
  const stage = page.getByTestId('water-studio-canvas')
  await expect(stage).toHaveAttribute('data-renderer', 'ready', { timeout: 45_000 })
  const canvas = stage.locator('canvas.water-simulation-canvas')
  await expect(canvas).toHaveAttribute('data-water-model', 'hydraulic-basin')
  // Software WebGL can occupy the main thread while compiling transmission;
  // allow that first state read to finish before evaluating the same thresholds.
  await expect.poll(async () => Number(await canvas.getAttribute('data-basin-wet-cells')), { timeout: 30_000 }).toBeGreaterThan(80)
  await expect.poll(async () => Number(await canvas.getAttribute('data-basin-time')), { timeout: 30_000 }).toBeGreaterThan(0.5)
  await page.getByRole('button', { name: '일시정지', exact: true }).click()
  const time = await canvas.getAttribute('data-basin-time')
  const stored = Number(await canvas.getAttribute('data-basin-stored-volume'))
  expect(stored).toBeGreaterThan(25)
  await page.screenshot({ path: testInfo.outputPath('deep-basin-desktop.png') })
  await page.getByRole('tab', { name: '재질', exact: true }).click()
  const height = page.getByRole('slider', { name: '벽 높이', exact: true })
  await height.focus(); await height.press('End')
  await expect(height).toHaveValue('1.75')
  expect(await canvas.getAttribute('data-basin-time')).toBe(time)
  await page.screenshot({ path: testInfo.outputPath('deep-basin-high-walls.png') })
  await height.press('Home')
  await page.getByRole('button', { name: '물 붓기 켜짐', exact: true }).click()
  await page.getByRole('button', { name: '재생', exact: true }).click()
  await expect.poll(async () => Number(await canvas.getAttribute('data-basin-stored-volume')), { timeout: 30_000 }).toBeLessThan(stored - 0.01)
  await page.getByRole('button', { name: '일시정지', exact: true }).click()
  await page.getByRole('button', { name: '2D', exact: true }).click()
  await expect(canvas).toHaveAttribute('data-water-model', 'position-based-free-surface')
  await page.getByRole('button', { name: '3D', exact: true }).click()
  await expect(canvas).toHaveAttribute('data-water-model', 'hydraulic-basin')
  expect(errors).toEqual([])
})

test('15.7 deep basin stays visible on a compact screen', async ({ page }, testInfo) => {
  test.setTimeout(120_000)
  await page.goto('/')
  const stage = page.getByTestId('water-studio-canvas')
  await expect(stage).toHaveAttribute('data-renderer', 'ready', { timeout: 45_000 })
  const canvas = stage.locator('canvas.water-simulation-canvas')
  await expect.poll(async () => Number(await canvas.getAttribute('data-basin-time')), { timeout: 30_000 }).toBeGreaterThan(0.3)
  await page.getByRole('button', { name: '일시정지', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('deep-basin-mobile.png') })
  await page.getByRole('button', { name: '튜닝 열기', exact: true }).click()
  await expect(page.getByRole('tab', { name: '물', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.screenshot({ path: testInfo.outputPath('deep-basin-mobile-controls.png') })
})
