import { test, expect } from '@playwright/test'
import { waterStartupTimeout, e2eTimeout } from './helpers/runtimeBudget'

test('exhibition starts, clears a real challenge, resumes and resets only its own save', async ({ page }) => {
  test.setTimeout(e2eTimeout(180_000))
  page.setDefaultTimeout(45_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/#/tripothon')
  await expect(page.getByTestId('tripothon-entry')).toBeVisible()
  await page.evaluate(() => {
    localStorage.setItem('mazecraft.challenges.v1', '{"stars":{"first-drop":2},"drafts":{}}')
    localStorage.setItem('mazecraft.cinematic.v1', 'off')
  })
  await page.getByRole('button', { name: '시연을 1단계부터 시작' }).click()
  await expect(page.getByTestId('craft-studio')).toBeVisible()
  const panel = page.getByRole('complementary', { name: '물길 크래프트' })
  if (!await panel.isVisible()) await page.getByRole('button', { name: '장치 목록 열기' }).click()
  await expect(panel.getByRole('list', { name: '목표' })).toContainText('30초 안에 종착 연못까지')
  await expect(panel.getByRole('button', { name: /2\..*잠김/ })).toBeDisabled()
  await panel.getByRole('button', { name: '연꽃 연못 추가' }).click()
  await expect(page.getByTestId('craft-canvas')).toHaveAttribute('data-renderer', 'ready', { timeout: waterStartupTimeout })
  await page.getByRole('combobox', { name: '재생 속도' }).selectOption('4')
  await page.getByRole('button', { name: '물 흘려보내기', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '스테이지 클리어' })).toBeVisible({ timeout: e2eTimeout(90_000) })
  await page.getByRole('button', { name: '계속 보기' }).click({ force: true })
  await page.getByRole('button', { name: '물에 띄우기' }).click()
  await page.getByRole('menuitem', { name: /고무오리/ }).click()
  await page.getByRole('button', { name: '메이즈크래프트 홈' }).click()
  await page.getByRole('button', { name: /챌린지 플레이/ }).click()
  await expect(page.getByTestId('craft-studio')).toBeVisible()
  if (!await panel.isVisible()) await page.getByRole('button', { name: '장치 목록 열기' }).click()
  await expect(panel.getByRole('list', { name: '목표' })).toContainText('시시오도시 3번')
  await page.getByRole('button', { name: '메이즈크래프트 홈' }).click()
  await page.getByRole('button', { name: '시연을 1단계부터 시작' }).click()
  await expect(page.getByTestId('craft-studio')).toBeVisible()
  if (!await panel.isVisible()) await page.getByRole('button', { name: '장치 목록 열기' }).click()
  await expect(panel.getByRole('list', { name: '목표' })).toContainText('30초 안에 종착')
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('mazecraft.challenges.v1')!).stars['first-drop'])).toBe(2)
  expect(errors).toEqual([])
})
