import { expect, test, type Page } from '@playwright/test'
import type { MazeProject } from '../src/core/maze'
import { openWaterGarden } from './helpers/navigation'

async function ready(page: Page) {
  await expect(page.getByTestId('water-studio-canvas')).toHaveAttribute('data-renderer', 'ready', { timeout: 90_000 })
  return page.locator('canvas.water-simulation-canvas')
}
/** Scenes open dry and paused; pause again if a test started the water. */
async function pause(page: Page) {
  const button = page.getByRole('button', { name: '일시정지', exact: true })
  if (await button.isVisible()) await button.click()
  await expect(page.getByRole('button', { name: '재생', exact: true })).toBeVisible()
}
async function flow(page: Page) {
  return page.locator('canvas.water-simulation-canvas').evaluate((canvas: HTMLCanvasElement) => ({ time: Number(canvas.dataset.particleTime), count: Number(canvas.dataset.particleCount), stored: Number(canvas.dataset.particleStoredVolume) }))
}

async function savedProject(page: Page): Promise<MazeProject> {
  await page.getByRole('button', { name: '미로 저장', exact: true }).click()
  await expect(page.getByRole('button', { name: '미로 저장 완료', exact: true })).toBeVisible()
  return page.evaluate(async () => {
    const database = await new Promise<IDBDatabase>((resolve, reject) => { const req = indexedDB.open('mazecraft-core'); req.onsuccess = () => resolve(req.result); req.onerror = () => reject(req.error) })
    const projects = await new Promise<MazeProject[]>((resolve, reject) => { const req = database.transaction('projects').objectStore('projects').getAll(); req.onsuccess = () => resolve(req.result); req.onerror = () => reject(req.error) })
    database.close()
    return projects[0]
  })
}
function wallDensity({ mazeGraph: g }: MazeProject) {
  return g.cells.reduce((count, cell) => count + Number(cell.active && cell.col + 1 < g.cols && g.cells[cell.index + 1].active && cell.walls.right)
    + Number(cell.active && cell.row + 1 < g.rows && g.cells[cell.index + g.cols].active && cell.walls.bottom), 0) / Math.max(g.rows, g.cols)
}

test('custom water retains the same gravity and inlet across 2D/3D, edits live, and resets paused', async ({ page }, info) => {
  test.setTimeout(240_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.addInitScript(() => localStorage.setItem('mazecraft.water-studio.v1', JSON.stringify({ source: 'generated', generator: { rows: 8, cols: 8, seed: 'live-water', shape: 'rectangle' } })))
  await openWaterGarden(page)
  await ready(page)
  await page.getByRole('button', { name: '3D', exact: true }).click()
  const canvas = await ready(page)
  await expect(canvas).toHaveAttribute('data-water-model', 'position-based-free-surface')
  await page.getByRole('button', { name: '물 흘려보내기', exact: true }).click()
  await expect.poll(async () => (await flow(page)).count, { timeout: 30_000 }).toBeGreaterThan(5)
  await pause(page)
  const paused = await flow(page)
  await page.getByRole('tab', { name: '색상', exact: true }).click()
  await expect(page.getByLabel('2D 격자 색상', { exact: true })).toHaveCount(0)
  await page.getByLabel('벽 색상', { exact: true }).fill('#315c88')
  await expect(canvas).toHaveAttribute('data-wall-color3d', '#315c88')
  await page.screenshot({ path: info.outputPath('custom-extruded-flow.png') })
  await page.getByRole('button', { name: '2D', exact: true }).click()
  expect(await flow(page)).toEqual(paused)
  await page.getByRole('tab', { name: '색상', exact: true }).click()
  await page.getByRole('button', { name: '흰색 배경', exact: true }).click()
  await expect(canvas).toHaveAttribute('data-background2d', 'white')
  await page.getByRole('tab', { name: '색상', exact: true }).click()
  await page.getByLabel('벽 색상', { exact: true }).fill('#243f60')
  await page.getByLabel('2D 격자 색상', { exact: true }).fill('#c1ccd6')
  await expect(canvas).toHaveAttribute('data-wall-color2d', '#243f60')
  await expect(canvas).toHaveAttribute('data-grid-color2d', '#c1ccd6')
  await page.getByRole('tab', { name: '미로', exact: true }).click()
  await page.getByRole('button', { name: '벽 직접 편집', exact: true }).click()
  const bounds = (await canvas.boundingBox())!
  await canvas.click({ position: { x: bounds.width * .5, y: bounds.height * .52 } })
  await ready(page)
  const edited = await flow(page)
  expect(edited.time).toBe(paused.time)
  expect(edited.count).toBe(paused.count)
  expect(edited.stored).toBeCloseTo(paused.stored, 6)
  await page.getByRole('button', { name: '벽 편집 중 · 완료', exact: true }).click()
  const original = await savedProject(page)
  const budget = await canvas.getAttribute('data-particle-capacity')
  const sampling = await canvas.getAttribute('data-particle-radius')
  const surfaceResolution = await canvas.getAttribute('data-surface-resolution')
  await page.screenshot({ path: info.outputPath('maze-density-8.png') })
  await page.getByRole('slider', { name: '미로 해상도', exact: true }).fill('16')
  await ready(page)
  await expect(page.getByLabel('현재 가로 칸 수', { exact: true })).toHaveValue('16')
  await ready(page)
  expect(await flow(page)).toEqual(paused)
  // A denser maze keeps the water it holds and may pour more to fill its channels.
  expect(Number(await canvas.getAttribute('data-particle-capacity'))).toBeGreaterThanOrEqual(Number(budget))
  await expect(canvas).toHaveAttribute('data-particle-radius', sampling!)
  await expect(canvas).toHaveAttribute('data-surface-resolution', surfaceResolution!)
  const finer = await savedProject(page)
  expect(wallDensity(finer)).toBeGreaterThan(wallDensity(original) * 1.8)
  expect(finer.mazeMetrics.solvable).toBe(true)
  await page.screenshot({ path: info.outputPath('maze-density-16.png') })
  await page.getByRole('slider', { name: '미로 해상도', exact: true }).fill('8')
  await expect(page.getByLabel('현재 가로 칸 수', { exact: true })).toHaveValue('8')
  await ready(page)
  const restored = await savedProject(page)
  expect(restored.mazeGraph).toEqual(original.mazeGraph)
  expect(await flow(page)).toEqual(paused)
  await page.screenshot({ path: info.outputPath('white-2d-live-edit.png') })
  await page.getByRole('button', { name: '3D', exact: true }).click()
  await expect(page.locator('canvas.water-simulation-canvas')).toHaveAttribute('data-wall-color3d', '#243f60')
  expect((await flow(page)).count).toBe(paused.count)
  await page.getByRole('button', { name: '물 다시 붓기', exact: true }).click()
  await expect(page.getByRole('button', { name: '재생', exact: true })).toBeVisible()
  await expect.poll(async () => (await flow(page)).time).toBe(0)
  await page.waitForTimeout(300)
  expect((await flow(page)).count).toBe(0)
  await page.getByRole('button', { name: '재생', exact: true }).click()
  await expect.poll(async () => (await flow(page)).count, { timeout: 30_000 }).toBeGreaterThan(0)
  expect(errors).toEqual([])
})

test('image-to-maze preserves photo aspect and interior gaps and opens in 2D, ready to flow', async ({ page }, info) => {
  test.setTimeout(180_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await openWaterGarden(page)
  await ready(page)
  await pause(page)
  await page.getByRole('tab', { name: '미로', exact: true }).click()
  await page.getByLabel('미로 모양 이미지 업로드').setInputFiles({ name: 'portrait-silhouette.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="160" height="240"><rect width="160" height="240" fill="white"/><path d="M25 220V125L55 95V25H105V95L135 125V220Z" fill="black"/><circle cx="80" cy="57" r="16" fill="white"/></svg>') })
  await expect(page.getByRole('img', { name: '이미지 모양 미리보기' })).toBeVisible()
  await page.getByLabel('이미지 해상도', { exact: true }).selectOption('32')
  await page.getByRole('button', { name: '이 이미지로 미로 만들기', exact: true }).click()
  const canvas = await ready(page)
  await expect(canvas).toHaveAttribute('data-view-mode', 'free-surface')
  await page.getByRole('button', { name: '물 흘려보내기', exact: true }).click()
  await expect.poll(async () => (await flow(page)).count, { timeout: 30_000 }).toBeGreaterThan(0)
  await pause(page)
  await page.getByRole('button', { name: '미로 저장', exact: true }).click()
  await expect(page.getByRole('button', { name: '미로 저장 완료', exact: true })).toBeVisible()
  const project = await page.evaluate(async () => {
    const database = await new Promise<IDBDatabase>((resolve, reject) => { const req = indexedDB.open('mazecraft-core'); req.onsuccess = () => resolve(req.result); req.onerror = () => reject(req.error) })
    const all = await new Promise<MazeProject[]>((resolve, reject) => { const req = database.transaction('projects').objectStore('projects').getAll(); req.onsuccess = () => resolve(req.result); req.onerror = () => reject(req.error) })
    database.close()
    return all.find(project => project.title === 'portrait-silhouette 물 미로')!
  })
  expect(project.shape.kind).toBe('image')
  expect(project.mazeGraph.rows).toBe(32)
  expect(project.mazeGraph.cols).toBe(21)
  expect(project.mazeGraph.cells.filter(cell => cell.active).length).toBeLessThan(32 * 21 * .8)
  expect(project.mazeGraph.cells[Math.floor(57 / 240 * 32) * 21 + 10].active).toBe(false)
  await page.screenshot({ path: info.outputPath('image-to-maze.png') })
  expect(errors).toEqual([])
})

test('15.9 mobile garden has an overhead inlet and controls outside the canvas', async ({ page }, info) => {
  test.setTimeout(120_000)
  await page.addInitScript(() => localStorage.setItem('mazecraft.water-studio.v1', JSON.stringify({ preset: 'garden', look: { theme: 'porcelain', light: 'daylight' }, color: '#16aeb7' })))
  await openWaterGarden(page)
  await ready(page)
  await page.getByRole('button', { name: '3D', exact: true }).click()
  const canvas = await ready(page)
  await page.getByRole('button', { name: '물 흘려보내기', exact: true }).click()
  await expect.poll(async () => Number(await canvas.getAttribute('data-basin-time')), { timeout: 30_000 }).toBeGreaterThan(0)
  await pause(page)
  const board = (await canvas.boundingBox())!, dock = (await page.locator('.ws-control-dock').boundingBox())!
  expect(dock.y).toBeGreaterThanOrEqual(board.y + board.height - 1)
  const dimensions = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth }))
  expect(dimensions.scroll).toBe(dimensions.width)
  await page.screenshot({ path: info.outputPath('mobile-bright-garden.png') })
  await page.getByRole('button', { name: '2D', exact: true }).click()
  const resolution = page.getByRole('slider', { name: '미로 해상도', exact: true })
  await expect(resolution).toBeVisible()
  await resolution.fill('12')
  await expect(page.locator('.ws-resolution-bar output')).toHaveText('12 × 12')
  await ready(page)
  const editedBoard = (await page.locator('canvas.water-simulation-canvas').boundingBox())!
  const bar = (await page.locator('.ws-resolution-bar').boundingBox())!
  expect(bar.y).toBeGreaterThanOrEqual(editedBoard.y + editedBoard.height - 1)
  expect(bar.x + bar.width).toBeLessThanOrEqual(dimensions.width)
  await page.screenshot({ path: info.outputPath('mobile-resolution-slider.png') })
})
