import { expect, test } from '@playwright/test'
import {
  branchingWaterProject, fallingWaterProject, importWaterProject, installWorkerProbe,
  numberAttribute, openParticleWater, pauseWater, readWaterState, readWorkerProbe,
} from './helpers/waterHarness'

test('2D와 3D 전환이 같은 물 입자·Worker·canvas와 정지 상태를 유지한다', async ({ page }, testInfo) => {
  test.setTimeout(90_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await installWorkerProbe(page)
  await importWaterProject(page, branchingWaterProject, 'high')
  const stage = await openParticleWater(page)
  await page.getByLabel('물 흐름 속도').selectOption('4')
  await expect.poll(() => numberAttribute(stage, 'data-elapsed-ms'), { timeout: 30_000 }).toBeGreaterThan(8_000)
  await pauseWater(page, stage)
  await page.getByRole('button', { name: '물 공급 멈추기' }).click()
  const before = await readWaterState(stage)
  const workers = await readWorkerProbe(page)
  const canvas = stage.locator('canvas.water-simulation-canvas')
  await canvas.evaluate(element => { element.dataset.e2eIdentity = 'shared-canvas' })
  const twoD = await canvas.screenshot()
  await page.screenshot({ path: testInfo.outputPath('water-translucent-2d-desktop.png') })
  await page.getByLabel('물 시뮬레이션 방식').selectOption('surface-3d')
  await expect(stage).toHaveAttribute('data-view-mode', 'surface-3d')
  await expect(stage).toHaveAttribute('data-fluid-model', 'position-based-free-surface')
  await expect(stage).toHaveAttribute('data-phase', 'paused')
  await expect(stage).toHaveAttribute('data-inflow', 'disabled')
  await expect(canvas).toHaveAttribute('data-e2e-identity', 'shared-canvas')
  expect(await readWaterState(stage)).toEqual(before)
  expect(await readWorkerProbe(page)).toEqual(workers)
  const threeD = await canvas.screenshot()
  expect(threeD.equals(twoD)).toBe(false)
  await page.screenshot({ path: testInfo.outputPath('water-translucent-3d-desktop.png') })
  await page.waitForTimeout(320)
  expect((await canvas.screenshot()).equals(threeD)).toBe(true)
  expect(await readWaterState(stage)).toEqual(before)
  await expect(page.locator('.water-status-copy, .water-success-cue')).toHaveCount(0)
  await page.getByRole('group', { name: '수면 표현' }).getByRole('button', { name: '역동' }).click()
  await expect(canvas).toHaveAttribute('data-e2e-identity', 'shared-canvas')
  await expect(stage).toHaveAttribute('data-water-surface-style', 'dynamic')
  expect(await readWaterState(stage)).toEqual(before)
  await page.getByLabel('물 흐름 속도').selectOption('1')
  await page.getByRole('button', { name: '물 시뮬레이션 재생' }).click()
  await expect.poll(() => numberAttribute(stage, 'data-elapsed-ms')).toBeGreaterThan(before.time + 400)
  // A request sent before pause may already have advanced the worker while its
  // snapshot was intentionally hidden. Measure stopped supply after that
  // request settles, then require continued motion without new water.
  const stopped = await readWaterState(stage)
  await expect.poll(() => numberAttribute(stage, 'data-elapsed-ms')).toBeGreaterThan(stopped.time + 400)
  expect(await numberAttribute(stage, 'data-injected-volume')).toBe(stopped.injected)
  await page.getByRole('button', { name: '물 공급 시작하기' }).click()
  await expect.poll(() => numberAttribute(stage, 'data-injected-volume')).toBeGreaterThan(stopped.injected)
  await pauseWater(page, stage)
  const afterResume = await readWaterState(stage)
  await page.getByLabel('물 시뮬레이션 방식').selectOption('free-surface')
  await expect(stage).toHaveAttribute('data-view-mode', 'free-surface')
  await expect(stage).toHaveAttribute('data-phase', 'paused')
  await expect(stage).toHaveAttribute('data-inflow', 'enabled')
  await expect(canvas).toHaveAttribute('data-e2e-identity', 'shared-canvas')
  expect(await readWaterState(stage)).toEqual(afterResume)
  expect(await readWorkerProbe(page)).toEqual(workers)
  expect(afterResume.error).toBeLessThan(1e-5)
  expect(errors).toEqual([])
})

test('low와 high가 같은 입자 솔버 입력을 사용하고 3D 유출량을 보존한다', async ({ page }) => {
  test.setTimeout(75_000)
  await installWorkerProbe(page)
  const layouts: string[] = []
  for (const quality of ['low', 'high'] as const) {
    await importWaterProject(page, fallingWaterProject, quality)
    const stage = await openParticleWater(page, 'surface-3d')
    await expect(stage).toHaveAttribute('data-quality', quality)
    await expect(stage).toHaveAttribute('data-physics-step-hz', '120')
    await expect(stage).toHaveAttribute('data-reached-exit', 'true', { timeout: 25_000 })
    await pauseWater(page, stage)
    const state = await readWaterState(stage)
    Object.values(state).forEach(value => expect(Number.isFinite(value)).toBe(true))
    expect(state.discharged).toBeGreaterThan(0)
    expect(Math.abs(state.injected - state.stored - state.discharged - state.escaped)).toBeLessThan(1e-5)
    expect(state.error).toBeLessThan(1e-5)
    const probe = await readWorkerProbe(page)
    expect(probe.fluidLayouts).toHaveLength(1)
    expect(probe.fluidInitKeys).toEqual(['generation,layout,type'])
    layouts.push(probe.fluidLayouts[0])
    await page.getByRole('button', { name: '물 시뮬레이션 닫기' }).click()
  }
  // Compare actual solver inputs, avoiding trajectories sampled at different
  // wall-clock instants under different graphics workloads.
  expect(layouts[1]).toBe(layouts[0])
})

test('15. 모바일 2D·3D 전환과 반복 닫기가 하나의 Worker와 WebGL을 회수한다', async ({ page }, testInfo) => {
  test.setTimeout(75_000)
  await page.setViewportSize({ width: 360, height: 800 })
  await installWorkerProbe(page)
  await importWaterProject(page, fallingWaterProject, 'low', true)
  for (let repeat = 0; repeat < 2; repeat++) {
    const before = await readWorkerProbe(page)
    const stage = await openParticleWater(page)
    await expect.poll(() => numberAttribute(stage, 'data-elapsed-ms')).toBeGreaterThan(2_000)
    await pauseWater(page, stage)
    const canvas = stage.locator('canvas.water-simulation-canvas')
    await canvas.evaluate(element => { element.dataset.e2eIdentity = 'mobile-shared' })
    const state = await readWaterState(stage)
    const mounted = await readWorkerProbe(page)
    expect(mounted.created).toBe(before.created + 1)
    expect(mounted.active).toBe(before.active + 1)
    if (repeat === 0) await page.screenshot({ path: testInfo.outputPath('water-translucent-2d-mobile.png') })
    await page.getByLabel('물 시뮬레이션 방식').selectOption('surface-3d')
    await expect(stage).toHaveAttribute('data-view-mode', 'surface-3d')
    await expect(canvas).toHaveAttribute('data-e2e-identity', 'mobile-shared')
    expect(await readWaterState(stage)).toEqual(state)
    expect(await readWorkerProbe(page)).toEqual(mounted)
    if (repeat === 0) await page.screenshot({ path: testInfo.outputPath('water-translucent-3d-mobile.png') })
    await expect(page.locator('.water-status-copy, .water-success-cue')).toHaveCount(0)
    const bounds = await page.getByRole('dialog').boundingBox()
    expect(bounds).not.toBeNull()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.y).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(360)
    expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(800)
    const controlsFit = await page.locator('.water-simulation-controls button, .water-simulation-controls select').evaluateAll(controls => controls.every(control => {
      const rect = control.getBoundingClientRect()
      return rect.width >= 44 && rect.height >= 44 && rect.left >= 0 && rect.right <= innerWidth && rect.top >= 0 && rect.bottom <= innerHeight
    }))
    expect(controlsFit).toBe(true)
    await page.getByRole('button', { name: '물 시뮬레이션 닫기' }).click()
    await expect(stage).toHaveCount(0)
    const closed = await readWorkerProbe(page)
    expect(closed.active).toBe(before.active)
    expect(closed.terminated).toBe(before.terminated + 1)
    expect(closed.contextsLost).toBeGreaterThan(before.contextsLost)
  }
})
